### PR TITLE
1.6.0

### PR DESCRIPTION
**Pull request by psined1**
v1.6.0 (Februray 11, 2018)

- Added display resolution method based on cookies, compliments to @halloamt, #37
- Added German translations, compliments to @halloamt, #37
- Added French translations, compliments to @ACANEXIA, #35
- Added validation and error reporting to DMP
- Added Fill mode for pictures, compliments @HansKatsman, #31
- Fixed SSRS report parameters, compliments @HansKatsman, #31

### CODE REVIEW

**Comment by halloamt** [comment]
Hi,

sorry for the late answer and thanks for accepting my PR :-) I like the possibility to choose between cookie and host identification for the displays.
There are two things I'd do differently. My code had the ability to do a transition from host based to cookie based. When the display does not have a cookie it looks for the host and sets a cookie. So when an admin decides to move to cookie based they do not havwe to visit every display and reregister it.
The other thing could be seen as a premature optimization. My code didn't iterate over all display when a valid cookie was found. That might reduce the server load a bit if there are many displays. But again, that might be seen as premature optiization.

Greetings from the Black Forest

**Comment by ACANEXIA** [comment]
Hi

Do you know when the version 1.6.0 will be available to download on the website ?

Thank you for your work

**Comment by psined1** [comment]
Hi @halloamt - 

We’ve had internal discussion on the best approach. We understand all your points. However, the goal of DM project is to offer solution for one and all. DM is used by many companies today.  There are companies that prefer static IP to cookies, whereas others care less. Both methods come with pros and cons. This really boils down to IT policies and design decisions. From that perspective, it is not our call as to what and when is more desired by our customers - transition from IP to cookies, or the other way round, or neither. Therefore, we’d rather give them a discrete choice, which they clearly know what to expect from. Of course, we could add “transitional” modes, but that might complicate things, especially as new methods will be offered, e.g. tenant-driven resolution, etc.

To your argument of preloading, it would certainly ease up the server. However, the call to load a display takes place once a day - not a very frequent event. Thus, performance gains are really moot in this case. On another hand, the loop method offers a simpler and cleaner code.

Hope this explains our decisions.

Once again, thanks for your contribution to DM project!

**Comment by psined1** [comment]
Hi @ACANEXIA - our team is in process of testing the code right now. You will know the new download is available after we merge this PR with master branch. We are a voulunteer-driven organization, so we only contribute as we are able to.

Also, please note, that this PR comes with additional translation symbols, which we’d appreciate if you contribute language for. 

Thanks, for your patience.

**Comment by halloamt** [comment]
@psined1 definitely, thanks for the explanation :-)

**Comment by DisplayMonkey** [comment]
1.6.0 released on DM website, pull request merged

**Pull request merged**
